apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: wns-vote-for-skill-microservices
build:
  artifacts:
  - image: dadtmt/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
        infer:
        - '**/*.ts'
        - '**/*.tsx'
  - image: dadtmt/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  - image: dadtmt/wilder
    context: wilder
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  - image: dadtmt/skill
    context: skill
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  
deploy:
  kubectl:
    manifests:
    - infra/deploy/client.yaml
    - infra/deploy/nats.yaml
    - infra/deploy/query-postgres.yaml
    - infra/deploy/wilder-mongo.yaml
    - infra/deploy/skill-mongo.yaml
    - infra/deploy/wilder.yaml
    - infra/deploy/query.yaml
    - infra/deploy/skill.yaml
    - infra/mapping/client.yaml
    - infra/mapping/query.yaml
    - infra/mapping/wilder.yaml
    - infra/mapping/skill.yaml
